### ISSUE TITLE
Hanging after splash, same error as practicalmeteor

### ISSUE THREAD

**Issue by mikepaszkiewicz** [serviewcare/meteor-wkwebview#1]
After doing a meteor reset, installing, and disabling Bitcode, I'm still running into the same problem as I was with the practicalmeteor package when running the project on emulator and device. 

`METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Error reading version file Error: Failed to resolve entry: file:///var/mobile/Containers/Data/Application/7EFE374F-36C9-4B02-9DED-04952D40827C/Library/NoCloud/meteor/version`

Further down some mentions of localhost:11234:
`2015-10-28 13:46:17.196 Habitat[256:14917] WkWebViewCordovaUpdate.startServer: arguments - (
    "/private/var/mobile/Containers/Bundle/Application/0EF7B604-60A9-4F14-9C93-1406D6A2AD75/Habitat.app/www/application/",
    "http://localhost:12344/"
)`

Safari command-R reset logs this in the inspector console, still hangs after splash.

`practicalmeteor:wkwebview: – "Success: wkwebview is the cordova web view."`

**Comment by jamielob** [comment]
Hi @mikepaszkiewicz - I just upgraded my project to 1.2.1 from 1.1.3 and this plugin is working great so far.  No splash screen hangs on device (haven't tried emulator).   Have you tried deleting your "local" directory that can be found inside the .meteor directory and the re-running?

**Comment by mikepaszkiewicz** [comment]
Jamie, 

I've tried deleting the local directory many times, and don't get any different results. Funny thing is, the behavior is persisting even when I remove the wkwebview package, so the root cause shouldn't be related. Since then I've even gone back to successful iOS build commits, and am getting the same output in xCode, which after digging deeper looks related to meteor/meteor#3709. 

Copied my packages folder into boilerplate meteor project, and while I'm getting the same error, the page still loads.

**Comment by Wenape** [comment]
@mikepaszkiewicz Are you using `meteor build .build` or `meteor run ios-device`? When using `meteor build .build`, my project also gets stuck at splashscreen and I get the same error as you. When using `meteor run ios-device`, again I get the same error, but the project runs with no problems. At least, until it receives an update and then it freezes just as with the first option.

**Comment by thedracle** [comment]
@Wenape,

It would be helpful to have a sample project that exhibits the above issue.

Our company has a fairly sophisticated project (Thousands of lines of code, and hundreds of packages + 10 or more cordova modules), using wkwebview.

We build with both ios-device and production deploys with meteor build. 

We aren't having issues with autoupdate or freezing, etc etc..

It possibly is some interaction with something else in your project.

Some other useful details would be OS Version (We test with 8.4, 9.0.2, and 9.1).

**Comment by mikepaszkiewicz** [comment]
@Wenape I'm actually running into problems with run ios-device, will give meteor-build a try now.

@thedracle Running on xCode 7.1 and iOS 8.4.1, and updating to 9.1 right now to give that a try. I'm in a similar situation with project size, the strange part is that it started happening out of nowhere without any changes to the repo. I'm going to give another machine a try as well and check back in.

**Comment by mikepaszkiewicz** [comment]
@Wenape meteor-build works consistently, and I repeatedly get the error above doing a run ios/ios-device.
